server:
  port: 0

info:
  component: Webseite
  description: Der Service liefert eine einfache Webseite, die andere Services zusammenfasst.

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/