server:
  port: 0

info:
  component: Trainer
  description: Service liefert Daten zu den Trainern eines Events.

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5