server:
  port: 8080

info:
  component: Trainer
  description: Service liefert Daten zu den Trainern des Events

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5