server:
  port: 0

info:
  component: Profilbild
  description: Service liefert ein Profilbild (aka Avatar) zu einer E-Mail-Adresse.

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5